"""added relationship EventTiket with Event

Revision ID: 6353f1c40afb
Revises: ea9232b10b26
Create Date: 2026-05-13 18:17:14.824367

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6353f1c40afb"
down_revision: Union[str, Sequence[str], None] = "ea9232b10b26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event_tickets", "event_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_tickets",
        sa.Column(
            "event_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
